maxTweetLength: 280
twitter4jProps:
  debug: true
  oauth.consumerKey: pSucyEwWhJo7paSXwmNBa8tcJ
  oauth.consumerSecret: VjyDuZgnBUQ3ds8FKhH72phVrgPYzmTv1gtMV94Gt9PsAfL9iD
  oauth.accesToken: 2422687974-UJIHMsSCnsz4ANfmnvg5xAdnZYUAyIYRlFBD3ti
  oauth.accesTokenSecret: UJuMyQ5efmhK7u2BNG5rA2x4wvihaDdKltXTbauCtTfuN

